name       : clj-kondo
version    : 2022.06.22
release    : 3
source     :
    - https://github.com/clj-kondo/clj-kondo/archive/refs/tags/v2022.06.22.tar.gz : e0dff13e5cd9677161a4762839bd2528218179cb5b7449d2c37a67e515d0039c
license    : EPL-1.0
component  : programming.tools
networking : yes
summary    : Clojure(script) and EDN linting
description: |
    clj-kondo performs static analysis on Clojure, ClojureScript and EDN, without the need of a running REPL. It informs you about potential errors while you are typing.
builddeps  :
    - leiningen
    - graalvm
    - openjdk-17
environment: |
    export GRAALVM_HOME=/usr/share/graalvm/
    export JAVA_HOME=/usr/share/graalvm/
    export JAVA_CMD=/usr/lib64/openjdk-17/bin/java
build      : |
    # make lein use a temporary location for deps
    sed -i '7 i :local-repo "/tmp/.m2/repo"' project.clj
    lein uberjar
    ./script/compile

install    : |
    install -Dm00755 ./clj-kondo $installdir/usr/bin/clj-kondo

