name       : clj-kondo
version    : 2022.08.03
release    : 4
source     :
    - https://github.com/clj-kondo/clj-kondo/archive/refs/tags/v2022.08.03.tar.gz : 4284a5ea775511dab1be73e5e4497dcff4d514eb71dfbafb79eb6e8db0e2df4f
license    : EPL-1.0
component  : programming.tools
networking : yes
summary    : Clojure(script) and EDN linting
description: |
    clj-kondo performs static analysis on Clojure, ClojureScript and EDN, without the need of a running REPL. It informs you about potential errors while you are typing.
builddeps  :
    - leiningen
    - graalvm
    - openjdk-17
environment: |
    export GRAALVM_HOME=/usr/share/graalvm/
    export JAVA_HOME=/usr/share/graalvm/
    export JAVA_CMD=/usr/lib64/openjdk-17/bin/java
build      : |
    # make lein use a temporary location for deps
    sed -i '7 i :local-repo "/tmp/.m2/repo"' project.clj
    lein uberjar
    ./script/compile

install    : |
    install -Dm00755 ./clj-kondo $installdir/usr/bin/clj-kondo

